apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: us-west1-docker.pkg.dev/test-teraform-vm/nginx-repo/nginx-gke:v1
        ports:
        - containerPort: 80

